### ISSUE TITLE
"jsa" not found in invocationSchemaHandler

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#105]
Then running the invocationSchemaHandler in both Python2 and Python3 as the main program and a valid descriptor returned the following error:

```
$ python invocationSchemaHandler.py -i schema/example_good.json
Traceback (most recent call last):
  File "invocationSchemaHandler.py", line 114, in validateSchema
    jsa.Draft4Validator.check_schema(s)
NameError: name 'jsa' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "invocationSchemaHandler.py", line 211, in <module>
    invSchema = generateInvocationSchema(desc) if given(args.input) else inSchema
  File "invocationSchemaHandler.py", line 106, in generateInvocationSchema
    if validateWrtMetaSchema: validateSchema( schema )
  File "invocationSchemaHandler.py", line 115, in validateSchema
    except jsa.SchemaError as se:
NameError: name 'jsa' is not defined
```

Any idea what jsa is supposed to be? It's not defined anywhere the name of an imported library, so I am not exactly sure where to poke next. Thanks

**Comment by natacha-beck** [comment]
take a look to my comment here: 

https://github.com/boutiques/boutiques/pull/104/files

**Comment by gkiar** [comment]
Thank you - I missed the name when I was splitting to multiline imports :)
