### ISSUE TITLE
List of numbers throwing an error

### ISSUE THREAD

**Issue by gregblt** [boutiques/boutiques#210]
Hi,

Bosh does not work with list of numbers as input:

Traceback (most recent call last):
  File "/home/gregory/anaconda3/bin/bosh", line 11, in <module>
    sys.exit(bosh())
  File "/home/gregory/anaconda3/lib/python3.6/site-packages/boutiques/bosh.py", line 273, in bosh
    out = execute(*params)
  File "/home/gregory/anaconda3/lib/python3.6/site-packages/boutiques/bosh.py", line 84, in execute
    executor.readInput(inp)
  File "/home/gregory/anaconda3/lib/python3.6/site-packages/boutiques/localExec.py", line 357, in readInput
    self.cmdLine = [ self._generateCmdLineFromInDict() ]
  File "/home/gregory/anaconda3/lib/python3.6/site-packages/boutiques/localExec.py", line 437, in _generateCmdLineFromInDict
    self._generateOutputFileNames()
  File "/home/gregory/anaconda3/lib/python3.6/site-packages/boutiques/localExec.py", line 411, in _generateOutputFileNames
    outputFileName = self._replaceKeysInTemplate(outputFileName,False,"keep",strippedExtensions)
  File "/home/gregory/anaconda3/lib/python3.6/site-packages/boutiques/localExec.py", line 379, in _replaceKeysInTemplate
    s_val += x+" "
TypeError: unsupported operand type(s) for +: 'int' and 'str'

I would say replacing `s_val += x+" "` by `s_val += str(x)+" "` would fix it if my understanding of the way bosh build list for the command line is correct?

Grégory

**Comment by glatard** [comment]
Thanks for reporting this! Could you post your descriptor, invocation and command-line so that we can reproduce the bug?

**Comment by glatard** [comment]
Thanks for reporting and solving this @gregblt. This should be fixed by #211.
