### ISSUE TITLE
Error on bosh exec simulate when output-files not defined

### ISSUE THREAD

**Issue by rmarkello** [boutiques/boutiques#300]
Using the latest version of boutiques (0.5.13), I've generated a descriptor that validates correctly (`bosh validate MYDESCRIPTOR.json` yields "OK") but fails on simulation. This failure is ostensibly because `output-files` is not defined in the descriptor.

The command I ran is:
```
[rmarkello: afni-integration]$ bosh exec simulate MYDESCRIPTOR.json -r 5
Traceback (most recent call last):
  File "/Users/rossmarkello/miniconda3/envs/afni/bin/bosh", line 11, in <module>
    sys.exit(bosh())
  File "/Users/rossmarkello/miniconda3/envs/afni/lib/python3.6/site-packages/boutiques/bosh.py", line 409, in bosh
    out = execute(*params)
  File "/Users/rossmarkello/miniconda3/envs/afni/lib/python3.6/site-packages/boutiques/bosh.py", line 155, in execute
    "changeUser": True})
  File "/Users/rossmarkello/miniconda3/envs/afni/lib/python3.6/site-packages/boutiques/localExec.py", line 148, in __init__
    self.outputs = self.desc_dict['output-files']  # Struct: [{id:}..,{id:}]
KeyError: 'output-files'
```

Tagging @gkiar since he asked me to post this issue!

**Comment by glatard** [comment]
I believe this is fixed in #301, thanks for reporting!
