### ISSUE TITLE
Non utf-8 encoded strings in stdout/stderr cause executor to crash

### ISSUE THREAD

**Issue by erinb90** [boutiques/boutiques#456]
When running `bosh exec launch`, if the `stdout` or `stderr` of the program contains non-utf-8 encoded characters, the executor crashes with the error:
```
Traceback (most recent call last):
  File "/home/erin/PycharmProjects/boutiques/tools/python/env/boutiques/bin/bosh", line 11, in <module>
    load_entry_point('boutiques', 'console_scripts', 'bosh')()
  File "/home/erin/PycharmProjects/boutiques/tools/python/boutiques/bosh.py", line 526, in bosh
    out = execute(*params)
  File "/home/erin/PycharmProjects/boutiques/tools/python/boutiques/bosh.py", line 140, in execute
    return executor.execute(results.volumes)
  File "/home/erin/PycharmProjects/boutiques/tools/python/boutiques/localExec.py", line 386, in execute
    container_command, container_location)
  File "/home/erin/PycharmProjects/boutiques/tools/python/boutiques/localExec.py", line 33, in __init__
    self.stderr = stderr.decode("utf=8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 1973: invalid start byte
```
Using Python 3.6 on Ubuntu.

**Comment by ramou** [comment]
I wonder where these came from? I suppose the solution is similar to what we did with search, or not specifying the decode without confirming it is supported (as we did for search).

**Comment by giorgioberardini1** [comment]
I have the same error using Power Shell. Did anyone find the solution?
