### ISSUE TITLE
Publish is getting an index error

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#559]
## Expected Behavior
for records to be published :)

## Current Behavior
```
$ bosh data publish
The records will be published to Zenodo as a data-set. This cannot be undone. Are you sure? (Y/n) Y
Traceback (most recent call last):
  File "/home/gkiar/code/env/gp/bin/bosh", line 11, in <module>
    sys.exit(bosh())
  File "/home/gkiar/code/env/gp/lib/python3.6/site-packages/boutiques/bosh.py", line 727, in bosh
    out = data(*params)
  File "/home/gkiar/code/env/gp/lib/python3.6/site-packages/boutiques/bosh.py", line 596, in data
    results.nexus)
  File "/home/gkiar/code/env/gp/lib/python3.6/site-packages/boutiques/dataHandler.py", line 105, in publish
    self._publish(self.record_files)
  File "/home/gkiar/code/env/gp/lib/python3.6/site-packages/boutiques/dataHandler.py", line 126, in _publish
    self._create_metadata(records_dict), self.zenodo_access_token)
  File "/home/gkiar/code/env/gp/lib/python3.6/site-packages/boutiques/dataHandler.py", line 195, in _create_metadata
    'relation': 'hasPart'} for k, v in records_dict.items()]
  File "/home/gkiar/code/env/gp/lib/python3.6/site-packages/boutiques/dataHandler.py", line 195, in <listcomp>
    'relation': 'hasPart'} for k, v in records_dict.items()]
IndexError: list index out of range
```

I encountered this issue yesterday, and will revisit it today to see if I can isolate if specific idiosyncrasies in my descriptors/invocations/records may be contributing to this?

## Environment (optional)
Python3.6, Boutiques version `0.5.22.post2`

**Comment by gkiar** [comment]
First sign of progress: there was a malformed DOI, only including the Zenodo portion. Replacing this with the full DOI path allowed us to find the records. Now, the following (unhelpful) error is appearing:

```bash
$ bosh data publish -v
[ INFO ] Using Zenodo endpoint https://zenodo.org
[ INFO (401) ] Zenodo is accessible
[ INFO (200) ] Authentication to Zenodo successful
[ INFO ] Zenodo access token saved in /home/gkiar/.boutiques
The records will be published to Zenodo as a data-set. This cannot be undone. Are you sure? (Y/n) Y
[ ERROR (504) ] Deposition failed
```
