### ISSUE TITLE
Loading descriptors has redundant operations and is broken with Zenodo DOI

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#591]
When adding a debug statement in `util/utils.py:27` (inside `loadJson`) and following along the execution trace, each time printing the value passed to the load utility, we can see the following two problems:
 1. The descriptor load utility is called **FIVE** times before crashing; and
 2. While for the first four of these loads uses the passed descriptor path, the last one uses the DOI in the descriptor which crashes the load utility, because it can't seem to handle the leading Zenodo digits.

```
$ bosh exec launch /home/gkiar/executions/nkirs/age_bmi/ref/Dipy-Tracking-and-Connectome-Generation/2020-03-06_15-38-20-264F71CM/dipy_tracking.json /home/gkiar/executions/nkirs/age_bmi/ref/Dipy-Tracking-and-Connectome-Generation/2020-03-06_15-38-20-264F71CM/invo-23_ref_sweep-prob-True.json -v /project/6008063/gkiar:/project/6008063/gkiar --imagepath ~/gkiar-dipy_tracking-v0.4.0.simg -s
> /home/gkiar/code/boutiques/tools/python/boutiques/util/utils.py(27)loadJson()
-> json_file = None
(Pdb) userInput
'/home/gkiar/executions/nkirs/age_bmi/ref/Dipy-Tracking-and-Connectome-Generation/2020-03-06_15-38-20-264F71CM/dipy_tracking.json'
(Pdb) c
> /home/gkiar/code/boutiques/tools/python/boutiques/util/utils.py(27)loadJson()
-> json_file = None
(Pdb) userInput
'/home/gkiar/executions/nkirs/age_bmi/ref/Dipy-Tracking-and-Connectome-Generation/2020-03-06_15-38-20-264F71CM/dipy_tracking.json'
(Pdb) c
> /home/gkiar/code/boutiques/tools/python/boutiques/util/utils.py(27)loadJson()
-> json_file = None
(Pdb) userInput
'/home/gkiar/executions/nkirs/age_bmi/ref/Dipy-Tracking-and-Connectome-Generation/2020-03-06_15-38-20-264F71CM/invo-23_ref_sweep-prob-True.json'
(Pdb) c
> /home/gkiar/code/boutiques/tools/python/boutiques/util/utils.py(27)loadJson()
-> json_file = None
(Pdb) userInput
'/home/gkiar/executions/nkirs/age_bmi/ref/Dipy-Tracking-and-Connectome-Generation/2020-03-06_15-38-20-264F71CM/dipy_tracking.json'
(Pdb) c
> /home/gkiar/code/boutiques/tools/python/boutiques/util/utils.py(27)loadJson()
-> json_file = None
(Pdb) userInput
'10.5281/zenodo.3699595'
(Pdb) c
Traceback (most recent call last):
  File "/home/gkiar/code/boutiques/tools/python/boutiques/util/utils.py", line 27, in loadJson
    json_file = None
  File "/home/gkiar/code/env/base/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/gkiar/code/env/base/lib/python3.6/site-packages/simplejson/decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
simplejson.errors.JSONDecodeError: Extra data: line 1 column 8 - line 1 column 23 (char 7 - 22)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gkiar/code/env/base/bin/bosh", line 11, in <module>
    load_entry_point('boutiques', 'console_scripts', 'bosh')()
  File "/home/gkiar/code/boutiques/tools/python/boutiques/bosh.py", line 907, in bosh
    out = execute(*params)
  File "/home/gkiar/code/boutiques/tools/python/boutiques/bosh.py", line 249, in execute
    "sandbox": results.sandbox})
  File "/home/gkiar/code/boutiques/tools/python/boutiques/localExec.py", line 160, in __init__
    self.summary = self._generateSummary(desc)
  File "/home/gkiar/code/boutiques/tools/python/boutiques/localExec.py", line 1225, in _generateSummary
    summary['descriptor-doi'] = self._findDOI(desc)
  File "/home/gkiar/code/boutiques/tools/python/boutiques/localExec.py", line 1242, in _findDOI
    if loadJson(doi) == self.desc_dict:
  File "/home/gkiar/code/boutiques/tools/python/boutiques/util/utils.py", line 27, in loadJson
    json_file = None
  File "/home/gkiar/code/boutiques/tools/python/boutiques/logger.py", line 10, in raise_error
    .format(message))
boutiques.util.utils.LoadError: [ ERROR ] Cannot parse input 10.5281/zenodo.3699595: file not found, invalid Zenodo ID, or invalid JSON object
```

## Expected Behavior
1. The descriptor load utility should only be called once and the loaded JSON passed around after that
2. The real descriptor DOI should be an acceptable way to load the descriptor, especially since this is the format that is returned from the publisher.

**Comment by glatard** [comment]
Refactoring could be as follows:
1. First-level API methods should only parse arguments and the descriptor, calling loadJson
2. Second-level API methods should take descriptors as dictionaries
3. First-level API methods can only call second-level ones

**Comment by gkiar** [comment]
This sounds like a good plan to me, @glatard . Should we have a Boutiques hackathon ahead of 1.0 release where we work on this and get Clowdr more in sync with the Boutiques stack (when I wrote it we couldn't pass descriptors as dictionaries or dois/`publish` and `data` didn't exist yet).

My plan would then be that you and I have a meeting first where we sit down with specific re-architectures that we want for both tools, map it all out, and then bring in the team with pizza for two days and do it.
