### ISSUE TITLE
Validator script fails for input objects with no "command-line-key"

### ISSUE THREAD

**Issue by johnflavin** [boutiques/boutiques#60]
When I run the `validator.rb` script, it fails when I have any inputs.

I'm on the `develop` branch, commit `3068fc9de710ecb3db71b034f63e95a1bfc51d3e`. I'm using the following descriptor for my test:
```json
{
    "name": "Test",
    "tool-version": "0.1",
    "description": "Test writing a Boutiques descriptor",
    "command-line": "static [dynamic]",
    "docker-image": "flavin/nothing",
    "schema-version": "0.3",
    "inputs": [
        {
            "id": "first_input",
            "name": "the input",
            "type": "String"
        }
    ],
    "groups": [],
    "output-files": []
}
```
When I attempt to validate it using `validator.rb`, the script fails.
```bash
[~/code/boutiques]$ tools/validator.rb schema/descriptor.schema.json ../boutiques-examples/test/boutiques.json
tools/validator.rb:61:in `include?': no implicit conversion of nil into String (TypeError)
	from tools/validator.rb:61:in `block in <main>'
	from tools/validator.rb:61:in `each'
	from tools/validator.rb:61:in `<main>'
```

If I remove the input, then it validates just fine.
```json
{
    "name": "Test",
    "tool-version": "0.1",
    "description": "Test writing a Boutiques descriptor",
    "command-line": "static [dynamic]",
    "docker-image": "flavin/nothing",
    "schema-version": "0.3",
    "inputs": [],
    "groups": [],
    "output-files": []
}
```
```bash
[~/code/boutiques]$ tools/validator.rb schema/descriptor.schema.json ../boutiques-examples/test/boutiques.json
["OK"]
```

UPDATE
If I keep the input, but add a `command-line-key`, then the script is fine. (Even if the value is blank.)

This works:
```json
"inputs": [
        {
            "id": "first_input",
            "name": "the input",
            "type": "String",
            "command-line-key": ""
        }
    ]
```
And this:
```json
"inputs": [
        {
            "id": "first_input",
            "name": "the input",
            "type": "String",
            "command-line-key": "[dynamic]"
        }
    ]
```
And this "works" in that it produces the expected error:
```json
"inputs": [
        {
            "id": "first_input",
            "name": "the input",
            "type": "String",
            "command-line-key": "[foo]"
        }
    ]
```

So it seems that even though `command-line-flag` is not a required property of the `input` object, the `validator.rb` script fails without it.

**Comment by ttaa9** [comment]
Thanks for catching that; the next version should fix it.
