### ISSUE TITLE
exception (instead of neat error message) when one value of a param both disables and requires one of output

### ISSUE THREAD

**Issue by MontrealSergiy** [boutiques/boutiques#649]
the code is wrongfully assumes that if one of values disables and requires some input then all the values both require and disable something. If this assumption does not hold, a keyerror exception might occur

```
        {
            "name":              "StringOption",
            "id":                "str",
            "description":       "just a string",
            "type":              "String",
            "optional":          true,
            "value-choices":     ["x", "y"],
            "value-requires":
                {"x":  ["du_report_out" ]},
            "value-disables":                {"x":  ["option_a" ]},
            "requires-inputs": ["option_upper_h"],
            "disables-inputs": ["option_h", "minput2"],
            "command-line-flag": "-H",
            "value-key":         "[FOLLOW_LINKS]"
        }
```

## Expected Behavior

exe
## Current Behavior

exception
```

## Environment (optional)
<!--- Information about the execution environment, in particular: Python version, Docker/Singularity version
 if relevant -->
exception
```
bosh validate boutiques.139-1.json
Traceback (most recent call last):
  File "/home/users/sboroday/bin/bosh", line 11, in <module>
    sys.exit(bosh())
  File "/home/users/sboroday/.local/lib/python3.6/site-packages/boutiques/bosh.py", line 962, in bosh
    out = validate(*params)
  File "/home/users/sboroday/.local/lib/python3.6/site-packages/boutiques/bosh.py", line 103, in validate
    sandbox=results.sandbox)
  File "/home/users/sboroday/.local/lib/python3.6/site-packages/boutiques/validator.py", line 368, in validate_descriptor
    for choice in inp["value-choices"]
  File "/home/users/sboroday/.local/lib/python3.6/site-packages/boutiques/validator.py", line 369, in <listcomp>
    for ids1 in inp["value-disables"][choice]
KeyError: 
```
## Context (optional)
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->
it does not affect me. 

## Possible fix (optional)
<!--- Not obligatory, but suggest an idea to fix the prroblem -->
perhaps
```
diff --git a/boutiques/validator.py b/boutiques/validator.py
index 9c35016..0a0f6b0 100755
--- a/boutiques/validator.py
+++ b/boutiques/validator.py
@@ -363,7 +363,7 @@ def validate_descriptor(descriptor, **kwargs):
                                 " and disables \"{2}\"")
                 errors += [msg_template.format(inp["id"], choice, ids1)
                            for choice in inp["value-choices"]
-                           for ids1 in inp["value-disables"][choice]
+                           for ids1 in inp["value-disables"].get(choice, [])
-                           if ids1 in inp["value-requires"][choice]]
+                           if ids1 in inp["value-requires"].get(choice, [])]
 
             for param in ["value-requires", "value-disables"]:

```



## Related issues (optional)
<!--- Link any related issue -->

**Comment by MontrealSergiy** [comment]
a complete descriptor for you https://github.com/MontrealSergiy/cbrain-plugins-test/blob/aea472bdf36eb7be35d78cb41cebe7f324265fb6/boutiques_descriptors/dependencyhell.json
