### ISSUE TITLE
Instructions to build containers

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#67]
We should improve the instructions to build containers as people are doing all sorts of fancy things. Here is a set of possible recommendations:
* Container must work as regular (non-root) user (they might be started as any user).
* Container must work non-interactively (without option `-it` in Docker).
* Container must not have an entrypoint.

Anything more to add at this point?

Does this apply to Singularity and rootfs?

**Comment by kofalt** [comment]
The any-user part is an interesting point: should we detect UIDs present in the environment? Demand a `nobody` user?

**Comment by glatard** [comment]
Good question. With Docker, running the container as UID 123 will produce files that belong to 123. So the only reasonable option for a platform is to run the container using the current user id (-u $UID) to make sure that the output files will belong to the platform. It means that the container should work as any user since there is no guarantee that a user with id $UID exists in the container. Moreover, we are not able to provide the value of $UID before the actual execution cluster is known. I can't think of a better recommendation for now, but maybe I'm missing something.

**Comment by glatard** [comment]
Starting a Docker container with `-u $UID` may create issues when $UID is not mapped to an existing user in the container *and* applications try to access the user name. See for instance the following error:
`
$ docker run --rm -u $UID  -it centos:latest
bash-4.2$ python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import getpass
>>> getpass.getuser()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/getpass.py", line 158, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1000'
`
Unless there is a better suggestion, I think we should enforce that the application runs in the Docker container under any UID, including non-existent ones. Also, I wonder how this issue should be addressed for Singularity and rootfs.

**Comment by kofalt** [comment]
> any UID, including non-existent one

I'm not sure how I feel about that, because one of my rough goals for this sort of standard is to have as few reasons as possible to need a wrapper script specifically for the standard. It would make it harder to drop your everyday algorithm into a boutique and run.

How would a boutique handle the any-UID situation? My guess would be a wrapper script that:

1. Checks if the UID exists;
2. Creates a dummy user if the UID is not found;
3. Ensure that files, folders, etc all have sufficient permission for that user;
4. Run the algorithm.

Let me know if I'm off base here. How about instead, a boutique can offer a non-zero UID? If present, the boutique will know it will be launched under that UID, if absent, anything goes.

**Comment by ttaa9** [comment]
Indeed, this is a pretty annoying issue concerning permissions. The current dev version of the execution wrapper script includes a `--changeUser` option, [which (crudely) creates a user in the container with the same uid and name as the current user before executing].(https://github.com/boutiques/boutiques/blob/develop/tools/localExec.py#L87)

This is how I got around the files being default owned by root after docker executes, and then subsequent programs being unable to access them... It is somewhat similar to @kofalt's suggestion.
